name: CI  # Nombre del workflow

on:
  push:  # Se ejecuta en cada push
  pull_request:  # Se ejecuta en cada PR

jobs:
  test:
    runs-on: ubuntu-latest  # Se ejecuta en Linux

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4  # Descarga el código

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install  # Cambia esto según tu proyecto

      - name: Ejecutar pruebas
        run: npm test  # Cambia esto según tu framework de pruebas

      - name: Mensaje final
        run: echo "✅ Pruebas completadas correctamente"