name: Mi Workflow Básico  # Nombre del workflow

on: 
  push:  # Se ejecuta cuando se hace un push a cualquier rama
  pull_request:  # Se ejecuta en cada pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Sistema donde se ejecutará el workflow

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4  # Descarga el código del repo

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Instala Node.js 18

      - name: Instalar dependencias
        run: npm install  # Instala dependencias si hay un package.json

      - name: Ejecutar pruebas
        run: npm test  # Corre los tests si existen

      - name: Mensaje final
        run: echo "Workflow ejecutado correctamente 🎉"